//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DifuntosApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DifuntosDBEntities : DbContext
    {
        public DifuntosDBEntities()
            : base("name=DifuntosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDifunto> tblDifunto { get; set; }
        public virtual DbSet<tblGeneral> tblGeneral { get; set; }
    
        public virtual ObjectResult<SPGetDifuntos_Result> SPGetDifuntos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetDifuntos_Result>("SPGetDifuntos");
        }
    }
}
